apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeloadbalancer2
spec:
  selector:
    matchLabels:
      app: kubeloadbalancer
  template:
    metadata:
      labels:
        app: kubeloadbalancer
    spec:
      containers:
      - name: kubeloadbalancer2
        image: nginx
        ports:
        - containerPort: 80
